### ISSUE TITLE
Update Caching 

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade-php#8]
@c-varberg Hey! So when we are caching, we want to cache for the specific page. Could you update wherever you have used the caching function to reflect this?

For example, in the "news_article_feed.php" file.

$sortedArticles = autoCache("sort_by_date", array($arrayOfArticles), 'feed_news_sorted_'.$_SERVER['REQUEST_URI'].$NumArticles);

For https://github.com/betheluniversity/cascade-php/issues/new
$_SERVER['REQUEST_URI'] = "/betheluniversity/cascade-php/issues/new"

**Comment by c-varberg** [comment]
I think I got all of them. I was thinking we could probably just add something into the autocache function itself to append the URI onto whatever name was passed in too. I might try doing that tomorrow

**Comment by c-schwarze** [comment]
Yeah lets do that.

**Comment by c-varberg** [comment]
Alright autoCache now adds the URIs on. I took out all the URIs I added to the autoCache calls yesterday. It's working for every example I've tested
